-- Table: public.GameData

-- DROP TABLE IF EXISTS public."GameData";

CREATE TABLE IF NOT EXISTS public."GameData"
(
    "Id" uuid NOT NULL,
    "MatchId" uuid NOT NULL,
    "Score_Map" integer,
    "Score_Home" integer,
    "Score_Away" integer,
    CONSTRAINT "PK_GameData" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GameData_Matches_MatchId" FOREIGN KEY ("MatchId")
        REFERENCES public."Matches" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."GameData"
    OWNER to "abr-prod_owner";
-- Index: IX_GameData_MatchId

-- DROP INDEX IF EXISTS public."IX_GameData_MatchId";

CREATE UNIQUE INDEX IF NOT EXISTS "IX_GameData_MatchId"
    ON public."GameData" USING btree
    ("MatchId" ASC NULLS LAST)
    TABLESPACE pg_default;
	
-- Table: public.GamePlayerData

-- DROP TABLE IF EXISTS public."GamePlayerData";

CREATE TABLE IF NOT EXISTS public."GamePlayerData"
(
    "GameDataEntityId" uuid NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" numeric(20,0),
    "Name" text COLLATE pg_catalog."default",
    "Mmr" numeric NOT NULL,
    "Rank" integer,
    "Side" integer NOT NULL,
    "GameTime" interval NOT NULL,
    "Mvp" boolean NOT NULL,
    CONSTRAINT "PK_GamePlayerData" PRIMARY KEY ("GameDataEntityId", "Id"),
    CONSTRAINT "FK_GamePlayerData_GameData_GameDataEntityId" FOREIGN KEY ("GameDataEntityId")
        REFERENCES public."GameData" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."GamePlayerData"
    OWNER to "abr-prod_owner";
	
-- Table: public.GamePlayerRoundData

-- DROP TABLE IF EXISTS public."GamePlayerRoundData";

CREATE TABLE IF NOT EXISTS public."GamePlayerRoundData"
(
    "GamePlayerDataGameDataEntityId" uuid NOT NULL,
    "GamePlayerDataId" integer NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" numeric(20,0),
    "Name" text COLLATE pg_catalog."default",
    "RoundNumber" integer NOT NULL,
    "Assists" integer NOT NULL,
    "Died" boolean NOT NULL,
    "FirstBlood" boolean NOT NULL,
    "Mvp" boolean NOT NULL,
    "Ace" boolean NOT NULL,
    "Won" boolean NOT NULL,
    "RoundTime" interval NOT NULL,
    CONSTRAINT "PK_GamePlayerRoundData" PRIMARY KEY ("GamePlayerDataGameDataEntityId", "GamePlayerDataId", "Id"),
    CONSTRAINT "FK_GamePlayerRoundData_GamePlayerData_GamePlayerDataGameDataEn~" FOREIGN KEY ("GamePlayerDataGameDataEntityId", "GamePlayerDataId")
        REFERENCES public."GamePlayerData" ("GameDataEntityId", "Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."GamePlayerRoundData"
    OWNER to "abr-prod_owner";
	
-- Table: public.WeaponData

-- DROP TABLE IF EXISTS public."WeaponData";

CREATE TABLE IF NOT EXISTS public."WeaponData"
(
    "GamePlayerRoundDataGamePlayerDataGameDataEntityId" uuid NOT NULL,
    "GamePlayerRoundDataGamePlayerDataId" integer NOT NULL,
    "GamePlayerRoundDataId" integer NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Type" integer NOT NULL,
    "Kills" integer NOT NULL,
    "HeadshotKills" integer NOT NULL,
    "ShotsFired" integer NOT NULL,
    "Hits" integer NOT NULL,
    "Headshots" integer NOT NULL,
    "Damage" integer NOT NULL,
    "FriendlyDamage" integer NOT NULL,
    CONSTRAINT "PK_WeaponData" PRIMARY KEY ("GamePlayerRoundDataGamePlayerDataGameDataEntityId", "GamePlayerRoundDataGamePlayerDataId", "GamePlayerRoundDataId", "Id"),
    CONSTRAINT "FK_WeaponData_GamePlayerRoundData_GamePlayerRoundDataGamePlaye~" FOREIGN KEY ("GamePlayerRoundDataGamePlayerDataGameDataEntityId", "GamePlayerRoundDataGamePlayerDataId", "GamePlayerRoundDataId")
        REFERENCES public."GamePlayerRoundData" ("GamePlayerDataGameDataEntityId", "GamePlayerDataId", "Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."WeaponData"
    OWNER to "abr-prod_owner";
	
-- Table: public.GadgetData

-- DROP TABLE IF EXISTS public."GadgetData";

CREATE TABLE IF NOT EXISTS public."GadgetData"
(
    "GamePlayerRoundDataGamePlayerDataGameDataEntityId" uuid NOT NULL,
    "GamePlayerRoundDataGamePlayerDataId" integer NOT NULL,
    "GamePlayerRoundDataId" integer NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Type" integer NOT NULL,
    "Used" integer NOT NULL,
    "Triggered" integer NOT NULL,
    "EnemyTriggered" integer NOT NULL,
    "Kills" integer NOT NULL,
    "Damage" integer NOT NULL,
    "FriendlyDamage" integer NOT NULL,
    "Destroyed" integer NOT NULL,
    "Healed" integer NOT NULL,
    CONSTRAINT "PK_GadgetData" PRIMARY KEY ("GamePlayerRoundDataGamePlayerDataGameDataEntityId", "GamePlayerRoundDataGamePlayerDataId", "GamePlayerRoundDataId", "Id"),
    CONSTRAINT "FK_GadgetData_GamePlayerRoundData_GamePlayerRoundDataGamePlaye~" FOREIGN KEY ("GamePlayerRoundDataGamePlayerDataGameDataEntityId", "GamePlayerRoundDataGamePlayerDataId", "GamePlayerRoundDataId")
        REFERENCES public."GamePlayerRoundData" ("GamePlayerDataGameDataEntityId", "GamePlayerDataId", "Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."GadgetData"
    OWNER to "abr-prod_owner";